### ISSUE TITLE
Needs to be recompiled with latest libnx

### ISSUE THREAD

**Issue by octopuserectus** [usineur/hota#2]
A great deal of your homebrew is affected: 
Controls don't work anymore. 
Temporary solution:
add:
`enable_deprecated_hid_mitm = u8!0x0`
In /atmosphere/config/system_settings.ini under [atmosphere]

**Comment by usineur** [comment]
https://twitter.com/usineur0/status/1173144847768854528

Just redownload it

**Comment by octopuserectus** [comment]
Oh, wow, sorry and thank you!
